### ISSUE TITLE
Issues installing this dependency

### ISSUE THREAD

**Issue by finleyowen** [square/SquarePointOfSaleSDK-iOS#100]
Hi, I opened an issue about this a while ago but closed it because I thought I had the wrong version of this SDK installed into my project. Basically, every now and then Xcode will not build my project and throw the following build error: "'openURL:' is deprecated: first deprecated in iOS 10.0". When it happens, the only way I've found to fix it is to remove the pod and then reinstall it and still this sometimes doesn't work. Could there be something wrong with the way I've configured my URL schemes, etc.? Thanks

**Comment by tichise** [comment]
The same phenomenon was reproduced in my environment, so I created a pull request to fix the problem.

**Comment by MikeSilvis** [comment]
Thank you both for reporting. It looks like if your deployment min target was set to iOS 11 and up this failed. I have deployed a fix https://github.com/square/SquarePointOfSaleSDK-iOS/releases/tag/3.5.1
