### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by jonaszmclaren** [square/SquarePointOfSaleSDK-iOS#105]
When are you planning on adding Swift Package Manager support?

**Comment by tichise** [comment]
I hope so, too.

**Comment by MikeSilvis** [comment]
Am working on this now. Would love assistance in verifying everything works as expected against master

https://github.com/square/SquarePointOfSaleSDK-iOS/pull/107

**Comment by tichise** [comment]
@MikeSilvis   Thank you. I'll use it today and give it a try.

**Comment by tichise** [comment]
@MikeSilvis I would like you to release an app with Swift Package support with a tag. It doesn't look like that has been done yet. 

https://github.com/square/SquarePointOfSaleSDK-iOS/releases

**Comment by MikeSilvis** [comment]
No I have not yet. Was waiting to see if everything is working as expected against master before cutting a release

**Comment by tichise** [comment]
Once it is added to release, I can download and verify it with the Swift package.

If it is difficult to add it to release, then I will download and verify it locally.

**Comment by MikeSilvis** [comment]
<img width="1512" alt="Screen Shot 2021-08-23 at 7 42 43 AM" src="https://user-images.githubusercontent.com/152323/130441563-4278acc8-2b4a-4e69-8b87-87c01984c461.png">

You should be able to add the package today and point it at master instead of a release version. This worked for me

**Comment by jonaszmclaren** [comment]
works now, thanks:)
