### ISSUE TITLE
Include of non-modular header inside framework module 'SquareRegisterSDK'

### ISSUE THREAD

**Issue by bz569** [square/SquarePointOfSaleSDK-iOS#37]
`NSURL+SCCAdditions.h` is a private header, but it is imported in `SquareRegisterSDK.h`. When using the SDK via git submodule, I get the compile error `Include of non-modular header inside framework module 'SquareRegisterSDK'`

**Comment by jmesmith** [comment]
Thanks for reporting this -- we'll get it fixed soon. For now you can make the header public to fix the compiler error.

**Comment by jmesmith** [comment]
This has been fixed in fa5c24a
