### ISSUE TITLE
Cancel button on card decline is covered by back-to-app button

### ISSUE THREAD

**Issue by nikarc** [square/SquarePointOfSaleSDK-iOS#41]
When the credit card declined view is shown in the register app, the cancel button is covered by ios's back-to-app button for my app. This makes it really hard to hit the cancel button, and i am usually taken back to my app prematurely.

image:
http://imgur.com/a/W5T98

**Comment by tristansokol** [comment]
Thanks for reporting! We are looking into this now and will have an update in the next few days.

**Comment by tristansokol** [comment]
Looks like a bug! We are working on getting a fix out.

**Comment by nikarc** [comment]
Awesome, thanks!

**Comment by tristansokol** [comment]
This issue will be fixed with and upcoming release of our Point of Sale app, in the next month or so. Thanks again for reporting!
