### ISSUE TITLE
Reference ID?

### ISSUE THREAD

**Issue by AztecWorks** [square/SquarePointOfSaleSDK-iOS#49]
Is there any way that I can pass a reference_id when launching square pos? That would then be included in the connect v2 list transaction rest response?

**Comment by kgleong** [comment]
Hi @aztecworks.  Currently, the ability to set a reference ID on the connect V2 transaciton object is not supported.  We do, however, have it on our roadmap of features, though a timeline for implementation has not been set yet.

As a workaround, are you aware of the [userInfoString parameter](https://github.com/square/SquarePointOfSaleSDK-iOS/blob/de5c9f3/SquarePointOfSaleSDK/SCCAPIRequest.h#L65)?

The `userInfoString` value is returned in the response, and a mapping from your reference IDs to a `transaction_id` or `client_transaction_id`, both of which are in the connect V2 transaction object, can be maintained by your app/service.
