### ISSUE TITLE
Error building fresh checkout via carthage

### ISSUE THREAD

**Issue by dethell** [square/SquarePointOfSaleSDK-iOS#54]
I'm trying to add the Square iOS SDK to our project and with a fresh checkout we are getting this error:

> *** Checking out SquarePointOfSaleSDK-iOS at "3.3.1"
> *** xcodebuild output can be found in /var/folders/rr/tbbc9jns1nn3y97gpd0sqgtc0000gn/T/carthage-xcodebuild.NM4REb.log
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/someuser/project/someapp/Carthage/Checkouts/SquarePointOfSaleSDK-iOS/SquarePointOfSaleSDK.xcodeproj -scheme SquarePointOfSaleSDKTests -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
> xcodebuild: error: Scheme SquarePointOfSaleSDKTests is not currently configured for the clean action.

This is using `carthage update --platform iOS SquarePointOfSaleSDK-iOS` as the command.

**Comment by Lyricalpanda** [comment]
Hi dethell,

What version of carthage are you using? I had success running the command using 0.24.0

**Comment by dethell** [comment]
Thank you for the response. Updating to 0.24.0 fixed the issue. I didn't realize I was so far behind in carthage updates.
