### ISSUE TITLE
LSApplicationQueriesSchemes

### ISSUE THREAD

**Issue by raghad54** [square/SquarePointOfSaleSDK-iOS#61]
when App run it gives an error in info.plist it's not available even I put it, what's going on ?

**Comment by kgleong** [comment]
@raghad54 have you 

1. Updated your Info.plist as directed [here](https://github.com/square/SquarePointOfSaleSDK-iOS#update-your-infoplist)?
2. Registered your app on the Square developer console as described [here](https://github.com/square/SquarePointOfSaleSDK-iOS#register-your-app-with-square)?

If so, please include the specific error you're receiving, so we can help get you connected.

**Comment by raghad54** [comment]
yea I did that all, also I still received this issue 
this's the error 
![Uploading Screen Shot 2018-02-26 at 9.19.18 PM.png…]()

**Comment by raghad54** [comment]
yes I did that all , but still receive this error : message " when I run said u must add LSApplicationQueriesSchemes"

**Comment by kgleong** [comment]
@raghad54 sounds like we might need to get more information on your account and how you've set things up.  Please email developers@help-messaging.squareup.com along with the email account that you registered your Square account with.
