### ISSUE TITLE
locationID:nil not work

### ISSUE THREAD

**Issue by darkengine** [square/SquarePointOfSaleSDK-iOS#63]
Point of Sale app will return with error when location_id is set to nil. In our case, Point of Sale app is login with merchant's account. And the payment request in our app is created with our Square Application ID. How can we pick a correct location ID in this case?

**Comment by StephenJosey** [comment]
You would need to go through the OAuth process to get access to their Square account, and then you can use our APIs to list the locations (by calling `ListLocations`) and allowing them to choose a location, or choosing one for them.
