### ISSUE TITLE
Is Custome Integration Possible? 

### ISSUE THREAD

**Issue by AnitaVPN** [square/SquarePointOfSaleSDK-iOS#65]
Hello there,

I am looking for Card Reader for my IOS POS system and i like the Square Card Reader but is there any way where i do not open square card reader app and integrate with my own app ?

Like just want  a customize integration for My POS system where the payment card reader interact with my app without navigating other apps?

**Comment by maulikpat** [comment]
@AnitaVPN  any suggestions ? I am looking for the same flow.

**Comment by kgleong** [comment]
@AnitaVPN and @maulikpat

Square’s Reader SDK was recently released and allows you to use Square hardware to take payments without app switching https://docs.connect.squareup.com/payments/readersdk/overview
