### ISSUE TITLE
No such module 'SquarePointOfSaleSDK'

### ISSUE THREAD

**Issue by leroz** [square/SquarePointOfSaleSDK-iOS#68]
Hi, I'm using cocoa pods to import **SquarePointofSaleSDK**.

I added the `import SquarePointOfSaleSDK` to the AppDelegate and it gives me an error:

`No such module 'SquarePointOfSaleSDK'`

Do you guys know how to handle this issue?

I specified the next platform info in the pod file: `platform :ios, '9.0'`

`pod 'Firebase/Core'`
`pod 'Firebase/Database'`

I'm Using Xcode: **Version 10.1 (10B61)** 

Thanks

**Comment by kgleong** [comment]
@leroz it looks like you're missing the line in your podfile to add the SquarePointOfSaleSDK to your Cocoapods project. 

Please add `pod 'SquarePointOfSaleSDK'`, run `pod install` and try again

**Comment by leroz** [comment]
Just in case, I've seen some people have had the same issue, what I did was:

**1st** a fresh clean of all pods for the project in terminal:
`sudo gem install cocoapods-deintegrate`
`pod deintegrate`
`pod clean`

also if you want to remove pod file and start fresh add the next command:
`rm Podfile`

**2nd**  I added the "use frameworks" line to the pod file, which I don't think is necessary but it helped me to solve the issue, just below the platform version:
`platform :ios, '9.0'`
`use_frameworks!`

**3rd** I installed and updated the pods in terminal:
`pod install`
`pod update`

After that it worked for me, hope this solution helps if anyone is having the same issue :)

and Thanks @kgleong for the feedback

**Comment by kgleong** [comment]
@leroz thanks for following up. Actually use_frameworks! is required. Good catch.
