### ISSUE TITLE
Bug In Square Success block - > IOS 13.3

### ISSUE THREAD

**Issue by Repair-Desk** [square/SquarePointOfSaleSDK-iOS#74]
after success, I didn't find it in the debugger of the success block. it is working on IOS 12. Please review my code below.

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        guard let sourceApplication = options[.sourceApplication] as? String,
            sourceApplication.hasPrefix("com.squareup.square") else {
                return false
        }
        
        do {
            let response = try SCCAPIResponse(responseURL: url)
            
            if let error = response.error {
                // Handle a failed request.
                print(error.localizedDescription)
        
                let alert = UIAlertController(title: "Error", message:error.localizedDescription, preferredStyle: UIAlertController.Style.alert)
                
                // add an action (button)
                alert.addAction(UIAlertAction(title: "OK", style: UIAlertAction.Style.default, handler: nil))
                
                // show the alert
                self.window?.rootViewController?.present(alert, animated: true, completion: nil)
                
            } else {
                // Handle a successful request.
                
                //here
             //   self.transDelegate?.updateTransationsResponse(transation: response.transactionID!)
                
                if response.isSuccessResponse{
                    
                    self.transDelegate?.updateTransationsResponse(transation: response.transactionID!)

                }
                else{
                    print("payment did not succesfull")
                }
                
            }
            
        } catch let error as NSError {
            // Handle unexpected errors.
            print(error.localizedDescription)
        }
        
        
        
        
        
        return true
    }

**Comment by cthorne91** [comment]
This became an issue for me starting at iOS 13.0. 

When you fetch `UIApplicationOpenURLOptionsSourceApplicationKey` from the `options` parameter on `- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options` you used to get the bundle identifier no matter what. However, starting in iOS 13 according to Apple:

> The value of this key is an NSString object containing the bundle ID of the app that made the request. If the request originated from another app belonging to your team, UIKit sets the value of this key to the ID of that app. If the team identifier of the originating app is different than the team identifier of the current app, the value of the key is nil.

Because square's app isn't part of your team, the bundle identifier will be nil in iOS 13.
To fix this, I had to start checking the url's path instead of the bundle identifier.

**Comment by MikeSilvis** [comment]
Generated https://github.com/square/SquarePointOfSaleSDK-iOS/pull/75 to assist with this issue

**Comment by MikeSilvis** [comment]
This is now resolved with the latest release
