### ISSUE TITLE
Carthage build fails for the last release (3.4.0)

### ISSUE THREAD

**Issue by orelpv** [square/SquarePointOfSaleSDK-iOS#79]
Last release broke carthage builds, causing this error:
`Dependency "SquarePointOfSaleSDK-iOS" has no shared framework schemes`

<img width="946" alt="image" src="https://user-images.githubusercontent.com/18669007/78942242-3feea700-7a87-11ea-8f46-62c5e5d006e3.png">

Locking the framework to 3.3.2 fixes the issue for now.

**Comment by MikeSilvis** [comment]
@Pahitos sorry about that, try again. I just uploaded the binary manually

**Comment by Pahitos** [comment]
@MikeSilvis hi, unfortunately I'm still running into the same issue :( 

From what I understand, there might be something wrong with the project/scheme config. Here are a few issues that might have some helpful details:
https://github.com/Carthage/Carthage/issues/1109
https://github.com/techprimate/TPPDF/issues/98

**Comment by MikeSilvis** [comment]
@Pahitos can you try clearing your Carthage cache?

```
m -rf ~/Library/Caches/org.carthage.CarthageKit
```

I just tried pulling and got it to work:

```
2.4.4 Test
 ➲  carthage update
Please update to the latest Carthage version: 0.34.0. You currently are on 0.33.0
*** Cloning SquarePointOfSaleSDK-iOS
*** Checking out SquarePointOfSaleSDK-iOS at "3.4.0"
*** xcodebuild output can be found in /var/folders/td/0lcyjgbx5cz4tj2tgmckz8mc0000gn/T/carthage-xcodebuild.TMNShi.log
*** Downloading SquarePointOfSaleSDK-iOS.framework binary at "Further iOS 13 Support"
```

**Comment by Pahitos** [comment]
@MikeSilvis still the same issue... What do you have in your cartfile? Is it just `github "Square/SquarePointOfSaleSDK-iOS"`? I also noticed you're running carthage 0.33.0, could the issue be with the newer version (0.34.0)?

**Comment by MikeSilvis** [comment]
@Pahitos mind bringing this to Slack? 

Our community: https://squ.re/2Hks3YE

**Comment by MikeSilvis** [comment]
You aren't by chance using:

```
carthage update --no-use-binaries
```

Are you?

**Comment by Pahitos** [comment]
@MikeSilvis ah, this was in fact the issue. We have a script that updates all our dependencies across multiple projects, which uses this. It seems to work fine without it for now, but is there any reason Square's SDK can't be updated when using this in the future?

**Comment by MikeSilvis** [comment]
Still trying to figure out the best course of action, but this is what i'm hitting: https://github.com/Carthage/Carthage/pull/2965

**Comment by Pahitos** [comment]
@MikeSilvis I'm now also running into an issue where I can't run the app on a physical iOS device. I think this might be [a different problem](https://github.com/Carthage/Carthage/issues/2530#issuecomment-408353675) than the above, but this doesn't happen when using `--no-use-binaries` with the older version. 

<img width="281" alt="image" src="https://user-images.githubusercontent.com/18669007/79283593-5bdaba00-7e86-11ea-88f0-e1926504db82.png">

I haven't tried, but I think this would also break the deployment of App Store builds. Do you mind reopening this issue please? And let me know if you need any other info that could help resolve this.

**Comment by MikeSilvis** [comment]
Shoot @Pahitos i know what this is. I’ll have to resubmit the binary as a FAT framework including both the simulator and device binary.

**Comment by MikeSilvis** [comment]
https://github.com/square/SquarePointOfSaleSDK-iOS/pull/82

I already re-uploaded the binary to the release. Try now! Sorry about all of this

**Comment by Pahitos** [comment]
@MikeSilvis no worries, it happens 😄 
So the normal `carthage update` seems to work and the app runs fine on a physical device, but when using `--no-use-binaries`, I still get the same error as  in my first post. I take it that will be fixed once https://github.com/Carthage/Carthage/pull/2965 is merged?

**Comment by MikeSilvis** [comment]
Exactly

**Comment by MikeSilvis** [comment]
Looks like this should now be resolved on Carthage's side https://github.com/Carthage/Carthage/pull/2965#issuecomment-642509493
