### ISSUE TITLE
Xcode 11.4.1 not able run on Simulator

### ISSUE THREAD

**Issue by maulikpat** [square/SquarePointOfSaleSDK-iOS#83]
Hi,

I am getting an error regarding the framework when I am trying to run the project.
![image](https://user-images.githubusercontent.com/2304770/80619434-8df92980-89f9-11ea-9e71-54417f9eef5e.png)

Though able to run on the device.

**Comment by StephenJosey** [comment]
Apologies for the delay. This looks like possibly an issue with XCode 11.4, not Square-specific. Take a look here and see if this helps: https://flutter.dev/docs/development/ios-project-migration
