### ISSUE TITLE
Question about the Square Register SDK 

### ISSUE THREAD

**Issue by ArEnSc** [square/SquarePointOfSaleSDK-iOS#93]
Hey it seems like this project used to be the SquareRegisterSDK,

in the SquareRegisterSDK in 2014 did you guys use the UIWebview and or it's api's ?  
We have a large product that we are migrating away from UIWebview usage.
We need confirmation otherwise we are going to be removing this SDK

**Comment by ArEnSc** [comment]
@1kgleong

**Comment by StephenJosey** [comment]
Not as far as I know, but if you could provide the specific version we can take a closer look. Also, I strongly recommend updating as there's been lots of changes/fixes since the initial release date (and we can guarantee no usage of UIWebView in the newer versions).

**Comment by ArEnSc** [comment]
Hey thanks for the quick response!  we will eventually look into an upgrade

**Comment by ArEnSc** [comment]
Hey I don't think the https://github.com/vend/SquareRegisterSDK-iOS ever had a version number ?

**Comment by StephenJosey** [comment]
Hm, do you have the `Podfile.lock`? What does it say in there?

**Comment by ArEnSc** [comment]
<img width="601" alt="Screen Shot 2020-10-24 at 2 53 13 PM" src="https://user-images.githubusercontent.com/6252325/97091299-fde31800-1608-11eb-94eb-4b3a3e481cf2.png">
Unfortunately we do not manage this specific library with carthage or cocoa pods heres a screen shot let me know if that helps!

**Comment by MikeSilvis** [comment]
i'm not really sure what the actionable items are for this.  Going to close, feel free to re-open if needed
