### ISSUE TITLE
There is no .xcodeproj to Drag

### ISSUE THREAD

**Issue by josehernandezv** [square/SquarePointOfSaleSDK-iOS#96]
I tried following the installation instructions but in the Pods folder there is no SquarePointOfSaleSDK.xcodeproj
When I try to use it I get an error
`Module 'SquarePointOfSaleSDK' not found`

**Comment by StephenJosey** [comment]
What happens when you use `pod install`, do you see it successfully being installed? It should be creating an `.xcodeproj` file somewhere if it installed successfully. If you're getting errors, please share them here so we can better assist.

**Comment by josehernandezv** [comment]
The Pods seem to install everything successfully but there is no .xcodeproj anywhere.
At the end I was able to make it work by replacing `@import SquarePointOfSaleSDK;` with 
`#import <SquarePointOfSaleSDK.h>`

**Comment by StephenJosey** [comment]
Thanks for sharing! I'll go ahead and close the issue in that case, but please let us know if you run into anything else.
